import type {
  Application,
  CandidateProfile,
  Company,
  IntegrationStatus,
  Job,
  NotificationPreference,
  SavedJob,
  ScanRun,
  ScoringWeights,
  SearchPreferences,
} from "./types";

// All records below are clearly-marked DEMO data used until real job-source
// integrations are connected. Companies are fictional on purpose.

const daysAgo = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

export const demoCompanies: Company[] = [
  {
    id: "c1",
    name: "Northwind Labs",
    logo: "NL",
    industry: "AI Research Platform",
    size: "250–500",
    headquarters: "London, UK",
    ukLocations: ["London", "Manchester"],
    sponsorshipStatus: "Confirmed",
    sponsorshipConfidence: 96,
    sponsorEvidence: [
      "Appears on the UK register of licensed sponsors (demo record)",
      "Job description states visa sponsorship is available",
      "Historically hires international graduates",
    ],
    openMatchingRoles: 3,
    previousApplications: 1,
    averageMatchScore: 91,
    priority: "High",
    followed: true,
    tags: ["Priority", "Sponsorship Friendly", "Recently Hiring", "Previously Applied"],
  },
  {
    id: "c2",
    name: "Halcyon Data",
    logo: "HD",
    industry: "Data Infrastructure",
    size: "80–150",
    headquarters: "Bristol, UK",
    ukLocations: ["Bristol", "Remote UK"],
    sponsorshipStatus: "Likely",
    sponsorshipConfidence: 78,
    sponsorEvidence: [
      "Sponsor licence found for parent entity (demo record)",
      "Salary band compatible with Skilled Worker thresholds",
    ],
    openMatchingRoles: 2,
    previousApplications: 0,
    averageMatchScore: 86,
    priority: "Medium",
    followed: true,
    tags: ["Sponsorship Friendly", "Startup", "Recently Hiring"],
  },
  {
    id: "c3",
    name: "Verity Payments",
    logo: "VP",
    industry: "Fintech",
    size: "1000+",
    headquarters: "London, UK",
    ukLocations: ["London", "Leeds"],
    sponsorshipStatus: "Possible",
    sponsorshipConfidence: 61,
    sponsorEvidence: [
      "Large employer with prior international hires (demo record)",
      "Job description does not mention sponsorship",
    ],
    openMatchingRoles: 2,
    previousApplications: 2,
    averageMatchScore: 81,
    priority: "Medium",
    followed: false,
    tags: ["Large Company", "Previously Applied"],
  },
  {
    id: "c4",
    name: "Beacon Cloud",
    logo: "BC",
    industry: "Cloud Platform",
    size: "500–1000",
    headquarters: "Reading, UK",
    ukLocations: ["Reading", "London", "Remote UK"],
    sponsorshipStatus: "Likely",
    sponsorshipConfidence: 82,
    sponsorEvidence: ["Sponsor licence on record (demo)", "Graduate scheme open to visa holders"],
    openMatchingRoles: 2,
    previousApplications: 0,
    averageMatchScore: 84,
    priority: "High",
    followed: true,
    tags: ["Priority", "Sponsorship Friendly", "Large Company"],
  },
  {
    id: "c5",
    name: "Orbital Health",
    logo: "OH",
    industry: "Health Tech",
    size: "150–250",
    headquarters: "Cambridge, UK",
    ukLocations: ["Cambridge"],
    sponsorshipStatus: "Unclear",
    sponsorshipConfidence: 44,
    sponsorEvidence: ["No sponsor licence evidence found yet (demo)"],
    openMatchingRoles: 1,
    previousApplications: 0,
    averageMatchScore: 76,
    priority: "Normal",
    followed: false,
    tags: ["Startup", "Recently Hiring"],
  },
  {
    id: "c6",
    name: "Ironclad Defence Systems",
    logo: "ID",
    industry: "Defence",
    size: "1000+",
    headquarters: "Portsmouth, UK",
    ukLocations: ["Portsmouth"],
    sponsorshipStatus: "No Sponsorship",
    sponsorshipConfidence: 8,
    sponsorEvidence: [
      "Job description requires UK citizenship (demo)",
      "Security clearance required",
    ],
    openMatchingRoles: 1,
    previousApplications: 0,
    averageMatchScore: 58,
    priority: "Normal",
    followed: false,
    tags: ["Large Company"],
  },
];

interface JobSeed {
  id: string;
  companyId: string;
  title: string;
  roleCategory: Job["roleCategory"];
  city: string;
  remote: Job["remote"];
  salary: [number, number] | null;
  posted: number;
  seniority: Job["seniority"];
  source: Job["source"];
  linkStatus: Job["linkStatus"];
  opportunity: number;
  match: number;
  breakdown: [number, number, number, number, number];
  matched: string[];
  missing: string[];
  partial: string[];
  sponsorship: Job["sponsorship"];
  required: string[];
  preferred: string[];
}

const seeds: JobSeed[] = [
  {
    id: "j1",
    companyId: "c1",
    title: "Machine Learning Engineer",
    roleCategory: "Machine Learning",
    city: "London",
    remote: "Hybrid",
    salary: [55000, 70000],
    posted: 0,
    seniority: "Junior",
    source: "Greenhouse",
    linkStatus: "Live",
    opportunity: 94,
    match: 94,
    breakdown: [96, 88, 100, 93, 82],
    matched: ["Python", "PyTorch", "AWS", "Docker", "SQL", "MLflow"],
    missing: ["Spark"],
    partial: ["Recommender systems"],
    sponsorship: {
      status: "Confirmed",
      confidence: 96,
      evidence: [
        "Company appears on the UK register of licensed sponsors (demo record)",
        "Job description states: \"We are able to sponsor Skilled Worker visas\"",
        "Salary band is above the Skilled Worker general threshold",
      ],
      warnings: [],
    },
    required: ["Python", "PyTorch", "Docker", "AWS", "SQL"],
    preferred: ["Spark", "MLflow", "Kubernetes"],
  },
  {
    id: "j2",
    companyId: "c4",
    title: "Cloud Solutions Engineer (Graduate)",
    roleCategory: "Cloud Engineering",
    city: "Reading",
    remote: "Hybrid",
    salary: [42000, 52000],
    posted: 0,
    seniority: "Graduate",
    source: "Workday",
    linkStatus: "Live",
    opportunity: 92,
    match: 90,
    breakdown: [92, 84, 100, 96, 74],
    matched: ["AWS", "Python", "Terraform", "Linux", "Networking"],
    missing: ["Azure"],
    partial: ["Customer-facing delivery"],
    sponsorship: {
      status: "Likely",
      confidence: 82,
      evidence: [
        "Sponsor licence on record (demo)",
        "Graduate scheme historically open to visa holders",
        "Role appears eligible for Skilled Worker sponsorship",
      ],
      warnings: ["Sponsorship is not explicitly confirmed in the advert"],
    },
    required: ["AWS", "Python", "Terraform", "Linux"],
    preferred: ["Azure", "Kubernetes", "Stakeholder communication"],
  },
  {
    id: "j3",
    companyId: "c2",
    title: "Data Engineer",
    roleCategory: "Data Engineering",
    city: "Remote UK",
    remote: "Remote",
    salary: [50000, 62000],
    posted: 1,
    seniority: "Junior",
    source: "Lever",
    linkStatus: "Live",
    opportunity: 90,
    match: 88,
    breakdown: [90, 82, 100, 92, 76],
    matched: ["Python", "SQL", "dbt", "Airflow", "AWS"],
    missing: ["Spark", "Kafka"],
    partial: ["Streaming pipelines"],
    sponsorship: {
      status: "Likely",
      confidence: 78,
      evidence: [
        "Sponsor licence found for parent entity (demo)",
        "Salary compatible with sponsorship requirements",
      ],
      warnings: ["Remote-UK contracts can complicate sponsorship"],
    },
    required: ["Python", "SQL", "Airflow"],
    preferred: ["Spark", "Kafka", "dbt"],
  },
  {
    id: "j4",
    companyId: "c1",
    title: "MLOps Engineer",
    roleCategory: "MLOps",
    city: "London",
    remote: "Hybrid",
    salary: [58000, 72000],
    posted: 2,
    seniority: "Associate",
    source: "Greenhouse",
    linkStatus: "Live",
    opportunity: 86,
    match: 85,
    breakdown: [88, 78, 100, 84, 74],
    matched: ["Docker", "Python", "CI/CD", "AWS", "MLflow"],
    missing: ["Kubernetes", "Terraform"],
    partial: ["Model monitoring at scale"],
    sponsorship: {
      status: "Confirmed",
      confidence: 94,
      evidence: ["Licensed sponsor (demo record)", "Advert mentions visa support"],
      warnings: [],
    },
    required: ["Python", "Docker", "CI/CD", "Kubernetes"],
    preferred: ["Terraform", "MLflow", "Prometheus"],
  },
  {
    id: "j5",
    companyId: "c3",
    title: "Data Scientist",
    roleCategory: "Data Science",
    city: "London",
    remote: "Hybrid",
    salary: [52000, 65000],
    posted: 2,
    seniority: "Junior",
    source: "Company Careers",
    linkStatus: "Live",
    opportunity: 84,
    match: 87,
    breakdown: [89, 80, 100, 90, 62],
    matched: ["Python", "SQL", "Machine Learning", "Statistics"],
    missing: ["Databricks"],
    partial: ["Payments domain"],
    sponsorship: {
      status: "Possible",
      confidence: 61,
      evidence: [
        "Large employer with prior international hires (demo)",
        "Advert is silent on sponsorship",
      ],
      warnings: ["Sponsorship may need to be confirmed with the recruiter"],
    },
    required: ["Python", "SQL", "Statistics"],
    preferred: ["Databricks", "A/B testing", "Payments experience"],
  },
  {
    id: "j6",
    companyId: "c2",
    title: "Analytics Engineer",
    roleCategory: "Data Analytics",
    city: "Bristol",
    remote: "Hybrid",
    salary: [45000, 55000],
    posted: 3,
    seniority: "Junior",
    source: "Ashby",
    linkStatus: "Possibly Live",
    opportunity: 82,
    match: 84,
    breakdown: [86, 78, 100, 88, 68],
    matched: ["SQL", "dbt", "Python", "BigQuery"],
    missing: ["Looker"],
    partial: ["Dimensional modelling"],
    sponsorship: {
      status: "Likely",
      confidence: 74,
      evidence: ["Sponsor licence on record (demo)"],
      warnings: ["Advert does not mention sponsorship"],
    },
    required: ["SQL", "dbt", "Python"],
    preferred: ["Looker", "Data modelling"],
  },
  {
    id: "j7",
    companyId: "c4",
    title: "Backend Software Engineer",
    roleCategory: "Backend Engineering",
    city: "London",
    remote: "Hybrid",
    salary: [50000, 65000],
    posted: 4,
    seniority: "Junior",
    source: "SmartRecruiters",
    linkStatus: "Live",
    opportunity: 81,
    match: 82,
    breakdown: [84, 76, 100, 86, 66],
    matched: ["Python", "PostgreSQL", "Docker", "REST APIs"],
    missing: ["Go", "gRPC"],
    partial: ["High-throughput systems"],
    sponsorship: {
      status: "Likely",
      confidence: 80,
      evidence: ["Licensed sponsor (demo)", "Role eligible for Skilled Worker route"],
      warnings: [],
    },
    required: ["Python", "PostgreSQL", "Docker"],
    preferred: ["Go", "gRPC", "AWS"],
  },
  {
    id: "j8",
    companyId: "c5",
    title: "AI Product Associate",
    roleCategory: "AI Product",
    city: "Cambridge",
    remote: "On-site",
    salary: [40000, 50000],
    posted: 5,
    seniority: "Graduate",
    source: "Company Careers",
    linkStatus: "Live",
    opportunity: 76,
    match: 79,
    breakdown: [78, 72, 100, 90, 58],
    matched: ["Python", "Prompt design", "Analytics"],
    missing: ["Clinical domain"],
    partial: ["Product discovery"],
    sponsorship: {
      status: "Unclear",
      confidence: 44,
      evidence: ["No sponsor licence evidence found yet (demo)"],
      warnings: ["Sponsorship likelihood is low-confidence — verify before applying"],
    },
    required: ["Analytics", "Communication", "Product sense"],
    preferred: ["Healthcare domain", "SQL"],
  },
  {
    id: "j9",
    companyId: "c3",
    title: "Platform Engineer",
    roleCategory: "Platform Engineering",
    city: "Leeds",
    remote: "Hybrid",
    salary: [48000, 60000],
    posted: 6,
    seniority: "Junior",
    source: "Job API",
    linkStatus: "Live",
    opportunity: 74,
    match: 76,
    breakdown: [76, 70, 100, 82, 60],
    matched: ["Linux", "Docker", "Python", "CI/CD"],
    missing: ["Kubernetes", "Ansible"],
    partial: ["Observability"],
    sponsorship: {
      status: "Possible",
      confidence: 58,
      evidence: ["Prior international hires (demo)"],
      warnings: ["Advert is silent on sponsorship"],
    },
    required: ["Linux", "Docker", "CI/CD"],
    preferred: ["Kubernetes", "Ansible", "Grafana"],
  },
  {
    id: "j10",
    companyId: "c5",
    title: "Solutions Engineer",
    roleCategory: "Solutions Engineering",
    city: "Cambridge",
    remote: "Hybrid",
    salary: null,
    posted: 7,
    seniority: "Associate",
    source: "Search API",
    linkStatus: "Unknown",
    opportunity: 71,
    match: 74,
    breakdown: [75, 70, 100, 78, 56],
    matched: ["Python", "SQL", "Presentations"],
    missing: ["Snowflake"],
    partial: ["Pre-sales experience"],
    sponsorship: {
      status: "Unclear",
      confidence: 41,
      evidence: ["No evidence gathered yet (demo)"],
      warnings: ["Job link could not be verified in the last scan"],
    },
    required: ["SQL", "Communication"],
    preferred: ["Snowflake", "Pre-sales"],
  },
  {
    id: "j11",
    companyId: "c6",
    title: "Software Engineer (Cleared)",
    roleCategory: "Software Engineering",
    city: "Portsmouth",
    remote: "On-site",
    salary: [45000, 58000],
    posted: 4,
    seniority: "Junior",
    source: "Company Careers",
    linkStatus: "Live",
    opportunity: 42,
    match: 68,
    breakdown: [72, 66, 100, 80, 40],
    matched: ["C++", "Python", "Linux"],
    missing: ["Security clearance"],
    partial: ["Embedded systems"],
    sponsorship: {
      status: "No Sponsorship",
      confidence: 6,
      evidence: [
        "Advert requires UK citizenship (demo)",
        "Security clearance required and cannot be obtained",
      ],
      warnings: ["Filtered out by your eligibility rules"],
    },
    required: ["C++", "Security clearance", "UK citizenship"],
    preferred: ["Embedded systems"],
  },
  {
    id: "j12",
    companyId: "c1",
    title: "AI Engineer (LLM Applications)",
    roleCategory: "AI Engineering",
    city: "London",
    remote: "Hybrid",
    salary: [60000, 75000],
    posted: 1,
    seniority: "Associate",
    source: "Greenhouse",
    linkStatus: "Live",
    opportunity: 91,
    match: 92,
    breakdown: [94, 84, 100, 88, 80],
    matched: ["Python", "LLMs", "RAG", "FastAPI", "AWS"],
    missing: ["Kafka"],
    partial: ["Vector database scaling"],
    sponsorship: {
      status: "Confirmed",
      confidence: 95,
      evidence: ["Licensed sponsor (demo)", "Advert offers visa sponsorship"],
      warnings: [],
    },
    required: ["Python", "LLMs", "FastAPI", "AWS"],
    preferred: ["Kafka", "Vector databases", "Evaluation frameworks"],
  },
];

const buildJob = (s: JobSeed): Job => {
  const company = demoCompanies.find((c) => c.id === s.companyId)!;
  return {
    id: s.id,
    companyId: s.companyId,
    title: s.title,
    roleCategory: s.roleCategory,
    location: `${s.city}, United Kingdom`,
    city: s.city,
    country: "United Kingdom",
    remote: s.remote,
    employmentType: "Full-time",
    salaryMin: s.salary?.[0],
    salaryMax: s.salary?.[1],
    currency: "GBP",
    description: `${company.name} is hiring a ${s.title} to join a small, senior team building production systems in ${company.industry.toLowerCase()}. You will own features end to end, work closely with product, and ship to real users every week.\n\nThis is DEMO content generated to illustrate the analysis experience. Once a real job source is connected, the original advert text will appear here verbatim.`,
    responsibilities: [
      `Design, build and ship ${s.roleCategory.toLowerCase()} work in production`,
      "Collaborate with product and engineering on scoping and delivery",
      "Improve reliability, testing and documentation of the systems you own",
      "Share findings and mentor others as the team grows",
    ],
    requiredSkills: s.required,
    preferredSkills: s.preferred,
    yearsExperience: s.seniority === "Graduate" ? "0–1 years" : "1–3 years",
    education: "Bachelor's degree in a technical subject or equivalent experience",
    seniority: s.seniority,
    industry: company.industry,
    datePosted: daysAgo(s.posted),
    dateDiscovered: daysAgo(Math.max(0, s.posted - 1) === s.posted ? s.posted : s.posted),
    source: s.source,
    originalUrl: `https://demo.jobs.example/${company.name.toLowerCase().replace(/\s+/g, "-")}/${s.id}`,
    applyUrl: `https://demo.jobs.example/${company.name.toLowerCase().replace(/\s+/g, "-")}/${s.id}/apply`,
    active: s.linkStatus !== "Expired" && s.linkStatus !== "Broken Link",
    lastVerified: daysAgo(0),
    linkStatus: s.linkStatus,
    opportunityScore: s.opportunity,
    match: {
      overall: s.match,
      skills: s.breakdown[0],
      requiredSkills: s.breakdown[0],
      preferredSkills: s.breakdown[0],
      responsibilities: s.breakdown[0],
      keywords: s.breakdown[0],
      whyRecommended: [],
      gapsSummary: s.missing.length ? `Missing ${s.missing.join(", ")}` : "No material gaps",
      learnedAdjustment: 0,
      experience: s.breakdown[1],
      education: s.breakdown[2],
      seniority: s.breakdown[3],
      domain: s.breakdown[4],

      matchedSkills: s.matched,
      missingSkills: s.missing,
      partialSkills: s.partial,
      strengths: [
        `Direct overlap on ${s.matched.slice(0, 3).join(", ")}`,
        `Seniority expectations line up with an early-career profile`,
        `Projects demonstrate shipped ${s.roleCategory.toLowerCase()} work`,
      ],
      risks: s.missing.length
        ? [`No evidence of ${s.missing.join(" or ")} in your CV`, "Domain experience is limited"]
        : ["Competition is likely high for this posting"],
      explanation: `Your profile lines up closely with the core requirements for this ${s.title} role — particularly ${s.matched.slice(0, 3).join(", ")}. The main gap is ${s.missing[0] ?? "domain depth"}, which is listed as ${s.preferred.includes(s.missing[0] ?? "") ? "preferred rather than essential" : "part of the day-to-day stack"}.`,
    },
    sponsorship: s.sponsorship,
    atsKeywords: [...s.required, ...s.preferred].slice(0, 8),
    atsCritical: s.required.slice(0, 5),
    atsUseful: s.preferred.slice(0, 5),
    technologies: [...s.required, ...s.preferred].slice(0, 10),
    analysisStatus: "completed",
    demo: true,

  };
};

export const demoJobs: Job[] = seeds.map(buildJob);

export const demoSavedJobs: SavedJob[] = [
  { jobId: "j4", folder: "Apply Tonight", savedOn: daysAgo(1) },
  { jobId: "j6", folder: "Need CV Tailoring", savedOn: daysAgo(2) },
  { jobId: "j5", folder: "Sponsorship Check", savedOn: daysAgo(2) },
  { jobId: "j9", folder: "Weekend", savedOn: daysAgo(3) },
];

export const savedFolders = [
  "Apply Tonight",
  "Weekend",
  "Dream Companies",
  "Need CV Tailoring",
  "Sponsorship Check",
  "Research Company",
];

export const demoApplications: Application[] = [
  {
    id: "a1",
    jobId: "j5",
    stage: "Interview",
    appliedOn: daysAgo(11),
    cvVersion: "CV v3 — Data Science",
    coverLetter: "Tailored — payments focus",
    notes: "Recruiter asked for availability next week.",
    recruiter: "Amelia Grant",
    nextStep: "Confirm interview slot",
    interviewDate: daysAgo(-3),
    needsFollowUp: true,
  },
  {
    id: "a2",
    jobId: "j7",
    stage: "Assessment",
    appliedOn: daysAgo(6),
    cvVersion: "CV v2 — Software Engineering",
    notes: "Take-home due in 3 days.",
    deadline: daysAgo(-3),
    nextStep: "Complete technical assessment",
    needsFollowUp: true,
  },
  {
    id: "a3",
    jobId: "j3",
    stage: "Applied",
    appliedOn: daysAgo(4),
    cvVersion: "CV v4 — Data Engineering",
    notes: "No response yet.",
    nextStep: "Follow up if silent after 10 days",
    needsFollowUp: false,
  },
  {
    id: "a4",
    jobId: "j9",
    stage: "Recruiter Screen",
    appliedOn: daysAgo(9),
    cvVersion: "CV v2 — Software Engineering",
    recruiter: "Tom Baker",
    nextStep: "Screen call Thursday",
    needsFollowUp: false,
  },
  {
    id: "a5",
    jobId: "j10",
    stage: "Rejected",
    appliedOn: daysAgo(21),
    cvVersion: "CV v1 — General",
    notes: "Rejected at CV stage — pre-sales experience required.",
    needsFollowUp: false,
  },
  {
    id: "a6",
    jobId: "j6",
    stage: "Saved",
    needsFollowUp: false,
  },
];

export const demoScanRuns: ScanRun[] = [
  {
    id: "s1",
    date: daysAgo(0),
    startedAt: "06:00",
    finishedAt: "06:12",
    sources: 9,
    discovered: 187,
    newJobs: 21,
    duplicatesRemoved: 34,
    expired: 6,
    analysed: 21,
    strongMatches: 6,
    errors: ["Workday connector: 2 pages timed out"],
  },
  {
    id: "s2",
    date: daysAgo(1),
    startedAt: "06:00",
    finishedAt: "06:09",
    sources: 9,
    discovered: 164,
    newJobs: 17,
    duplicatesRemoved: 28,
    expired: 4,
    analysed: 17,
    strongMatches: 5,
    errors: [],
  },
  {
    id: "s3",
    date: daysAgo(2),
    startedAt: "06:00",
    finishedAt: "06:14",
    sources: 8,
    discovered: 143,
    newJobs: 18,
    duplicatesRemoved: 31,
    expired: 9,
    analysed: 18,
    strongMatches: 6,
    errors: ["Search API: rate limited"],
  },
];

export const demoProfile: CandidateProfile = {
  name: "Jaswanth",
  headline: "Early-career ML & Data Engineer · London",
  summary:
    "Graduate engineer with hands-on experience building and deploying machine learning and data pipelines on AWS. Comfortable across Python, SQL and containerised deployment.",
  targetRoles: [
    "Data Science",
    "Machine Learning",
    "AI Engineering",
    "MLOps",
    "Data Engineering",
    "Software Engineering",
    "Cloud Engineering",
    "Solutions Engineering",
    "AI Product",
  ],
  preferredLocations: ["London", "Greater London", "Remote UK", "Hybrid UK"],
  remotePreference: ["Hybrid", "Remote"],
  salaryExpectation: { min: 40000, max: 70000 },
  industries: ["AI", "Fintech", "Cloud", "Health Tech"],
  preferredSeniority: ["Graduate", "Junior", "Associate", "Mid"],
  skills: ["Python", "SQL", "Machine Learning", "Docker", "Airflow", "dbt", "CI/CD", "FastAPI"],
  languages: ["Python", "SQL", "TypeScript", "C++"],
  cloud: ["AWS", "GCP"],
  databases: ["PostgreSQL", "BigQuery", "Redis"],
  mlSkills: ["PyTorch", "scikit-learn", "MLflow", "LLMs", "RAG"],
  yearsExperience: 1.5,
  education: "MSc Data Science, University of Leeds",
  certifications: ["AWS Certified Cloud Practitioner"],
  workAuthorization: "Requires sponsorship",
  visaType: "Graduate Route (expires in 14 months)",
  sponsorshipRequiredNow: false,
  sponsorshipRequiredLater: true,
  cvVersions: [
    "CV v1 — General",
    "CV v2 — Software Engineering",
    "CV v3 — Data Science",
    "CV v4 — Data Engineering",
  ],
};

export const demoSearchPreferences: SearchPreferences = {
  targetTitles: [
    "Data Scientist",
    "Machine Learning Engineer",
    "AI Engineer",
    "MLOps Engineer",
    "Data Engineer",
    "Backend Engineer",
    "Cloud Engineer",
    "Solutions Engineer",
  ],
  excludedTitles: ["Head of", "Principal", "Staff", "Director", "Sales Development"],
  locations: ["London", "Greater London", "Remote UK", "Hybrid UK"],
  remotePreference: ["Hybrid", "Remote"],
  salaryMin: 38000,
  jobAgeDays: 7,
  minMatchScore: 70,
  minOpportunityScore: 60,
  minSponsorshipConfidence: 40,
  excludedIndustries: ["Defence", "Gambling"],
  excludedCompanies: [],
  rejectCitizenshipRequired: true,
  rejectSecurityClearance: true,
  rejectAboveSeniority: true,
};

export const defaultWeights: ScoringWeights = {
  cvMatch: 40,
  sponsorshipFit: 20,
  seniorityFit: 10,
  locationFit: 10,
  recency: 10,
  companyPriority: 5,
  salaryFit: 5,
};

export const demoNotificationPreferences: NotificationPreference[] = [
  { category: "Daily Job Digest", channels: ["Email"], enabled: true },
  { category: "Apply ASAP Job", channels: ["Email", "Browser"], enabled: true },
  { category: "High Sponsorship Match", channels: ["Email"], enabled: true },
  { category: "New Job at Priority Company", channels: ["Email"], enabled: true },
  { category: "Saved Job Expiring", channels: ["Browser"], enabled: true },
  { category: "Application Follow-up", channels: ["Email"], enabled: true },
  { category: "Interview Reminder", channels: ["Email", "Browser"], enabled: false },
];

export const demoIntegrations: IntegrationStatus[] = [
  { name: "Greenhouse", kind: "Job Source", connected: false, detail: "Public board API — needs board tokens" },
  { name: "Lever", kind: "Job Source", connected: false, detail: "Postings API — needs company slugs" },
  { name: "Workday", kind: "Job Source", connected: false, detail: "Per-tenant endpoints required" },
  { name: "SmartRecruiters", kind: "Job Source", connected: false, detail: "Public postings API" },
  { name: "Ashby", kind: "Job Source", connected: false, detail: "Job board API" },
  { name: "Company career pages", kind: "Job Source", connected: false, detail: "Watchlist crawler" },
  { name: "AI job analysis", kind: "AI", connected: false, detail: "Runs server-side once enabled" },
  { name: "Email digest", kind: "Notification", connected: false, detail: "Daily 06:15 digest" },
  { name: "Telegram / Slack", kind: "Notification", connected: false, detail: "Optional channels" },
  { name: "Daily scan scheduler", kind: "Scheduler", connected: false, detail: "06:00 UK daily scan" },
];

export const learnedPreferences = [
  { label: "Prefers hybrid roles in London", evidence: "12 Interested · 3 Not interested" },
  { label: "Down-ranks on-site only roles outside London", evidence: "7 Wrong Location" },
  { label: "Down-ranks roles requiring 5+ years", evidence: "9 Too Senior" },
  { label: "Up-ranks sponsorship-confirmed employers", evidence: "15 Interested" },
];
