/**
 * The fixed 400-company target universe for direct career-source monitoring.
 *
 * This file is a registry of *names only*: being listed here confers no status
 * whatsoever. A company is only ever monitored after its official career source
 * has been individually discovered, hit for real vacancies and validated. Every
 * company that cannot be validated is reported honestly with its reason.
 *
 * Format: "Company name|primary domain|sector".
 */

export type CompanyGroup = "established" | "startup";

export interface TargetCompany {
  name: string;
  domain: string | null;
  sector: string;
  group: CompanyGroup;
}

const ESTABLISHED = [
  "Google|google.com|Technology",
  "Microsoft|microsoft.com|Technology",
  "Amazon|amazon.com|Technology",
  "Apple|apple.com|Technology",
  "Meta|meta.com|Technology",
  "Netflix|netflix.com|Media",
  "NVIDIA|nvidia.com|Semiconductors",
  "IBM|ibm.com|Technology",
  "Oracle|oracle.com|Enterprise software",
  "SAP|sap.com|Enterprise software",
  "Salesforce|salesforce.com|Enterprise software",
  "Adobe|adobe.com|Software",
  "Intel|intel.com|Semiconductors",
  "AMD|amd.com|Semiconductors",
  "Qualcomm|qualcomm.com|Semiconductors",
  "Cisco|cisco.com|Networking",
  "Dell Technologies|dell.com|Hardware",
  "HP|hp.com|Hardware",
  "Hewlett Packard Enterprise|hpe.com|Enterprise IT",
  "Broadcom|broadcom.com|Semiconductors",
  "ServiceNow|servicenow.com|Enterprise software",
  "Workday|workday.com|Enterprise software",
  "Snowflake|snowflake.com|Data platform",
  "Databricks|databricks.com|Data platform",
  "Palantir|palantir.com|Data platform",
  "Atlassian|atlassian.com|Software",
  "Autodesk|autodesk.com|Software",
  "Intuit|intuit.com|Fintech",
  "PayPal|paypal.com|Payments",
  "Visa|visa.com|Payments",
  "Mastercard|mastercard.com|Payments",
  "American Express|americanexpress.com|Financial services",
  "JPMorgan Chase|jpmorganchase.com|Investment banking",
  "Goldman Sachs|goldmansachs.com|Investment banking",
  "Morgan Stanley|morganstanley.com|Investment banking",
  "Barclays|barclays.co.uk|Banking",
  "HSBC|hsbc.com|Banking",
  "Lloyds Banking Group|lloydsbankinggroup.com|Banking",
  "NatWest Group|natwestgroup.com|Banking",
  "Santander UK|santander.co.uk|Banking",
  "Standard Chartered|sc.com|Banking",
  "Nationwide Building Society|nationwide.co.uk|Banking",
  "Schroders|schroders.com|Asset management",
  "Legal & General|legalandgeneral.com|Insurance",
  "Aviva|aviva.com|Insurance",
  "M&G|mandg.com|Asset management",
  "Phoenix Group|thephoenixgroup.com|Insurance",
  "London Stock Exchange Group|lseg.com|Financial data",
  "Bloomberg|bloomberg.com|Financial data",
  "S&P Global|spglobal.com|Financial data",
  "Moody's|moodys.com|Financial data",
  "MSCI|msci.com|Financial data",
  "Deloitte|deloitte.com|Professional services",
  "PwC|pwc.com|Professional services",
  "EY|ey.com|Professional services",
  "KPMG|kpmg.com|Professional services",
  "Accenture|accenture.com|Consulting",
  "Capgemini|capgemini.com|Consulting",
  "Infosys|infosys.com|IT services",
  "Tata Consultancy Services|tcs.com|IT services",
  "Wipro|wipro.com|IT services",
  "HCLTech|hcltech.com|IT services",
  "Cognizant|cognizant.com|IT services",
  "Atos|atos.net|IT services",
  "Sopra Steria|soprasteria.co.uk|IT services",
  "CGI|cgi.com|IT services",
  "Fujitsu|fujitsu.com|IT services",
  "NTT Data|nttdata.com|IT services",
  "Kainos|kainos.com|IT services",
  "BT Group|bt.com|Telecoms",
  "Vodafone|vodafone.com|Telecoms",
  "Virgin Media O2|virginmediao2.co.uk|Telecoms",
  "Sky|sky.com|Media",
  "ITV|itv.com|Media",
  "BBC|bbc.co.uk|Media",
  "Channel 4|channel4.com|Media",
  "Rolls-Royce|rolls-royce.com|Aerospace",
  "BAE Systems|baesystems.com|Defence",
  "Leonardo UK|leonardo.com|Defence",
  "Thales UK|thalesgroup.com|Defence",
  "Airbus|airbus.com|Aerospace",
  "Babcock International|babcockinternational.com|Defence",
  "QinetiQ|qinetiq.com|Defence",
  "GKN Aerospace|gknaerospace.com|Aerospace",
  "Jaguar Land Rover|jaguarlandrover.com|Automotive",
  "Aston Martin|astonmartin.com|Automotive",
  "Bentley Motors|bentleymotors.com|Automotive",
  "McLaren|mclaren.com|Automotive",
  "Nissan UK|nissan.co.uk|Automotive",
  "Ford|ford.com|Automotive",
  "Dyson|dyson.com|Consumer technology",
  "Arm|arm.com|Semiconductors",
  "Imagination Technologies|imaginationtech.com|Semiconductors",
  "Renishaw|renishaw.com|Engineering",
  "Smiths Group|smiths.com|Engineering",
  "Siemens|siemens.com|Industrial technology",
  "GE Aerospace|geaerospace.com|Aerospace",
  "Schneider Electric|se.com|Energy technology",
  "ABB|abb.com|Industrial technology",
  "Bosch|bosch.com|Industrial technology",
  "Philips|philips.com|Health technology",
  "Ericsson|ericsson.com|Telecoms equipment",
  "Nokia|nokia.com|Telecoms equipment",
  "Samsung|samsung.com|Consumer technology",
  "Sony|sony.com|Consumer technology",
  "Tesco|tesco.com|Retail",
  "Sainsbury's|sainsburys.co.uk|Retail",
  "Asda|asda.com|Retail",
  "Morrisons|morrisons.com|Retail",
  "Marks & Spencer|marksandspencer.com|Retail",
  "John Lewis Partnership|johnlewispartnership.co.uk|Retail",
  "Ocado Group|ocadogroup.com|Retail technology",
  "Next|next.co.uk|Retail",
  "Boots|boots.com|Retail",
  "Kingfisher|kingfisher.com|Retail",
  "Currys|currys.co.uk|Retail",
  "JD Sports|jdplc.com|Retail",
  "Frasers Group|frasers.group|Retail",
  "ASOS|asos.com|E-commerce",
  "Burberry|burberry.com|Luxury retail",
  "Unilever|unilever.com|Consumer goods",
  "Diageo|diageo.com|Consumer goods",
  "AstraZeneca|astrazeneca.com|Pharmaceuticals",
  "GSK|gsk.com|Pharmaceuticals",
  "Reckitt|reckitt.com|Consumer goods",
  "Haleon|haleon.com|Consumer health",
  "Pfizer|pfizer.com|Pharmaceuticals",
  "Johnson & Johnson|jnj.com|Healthcare",
  "Roche|roche.com|Pharmaceuticals",
  "Novartis|novartis.com|Pharmaceuticals",
  "Sanofi|sanofi.com|Pharmaceuticals",
  "BP|bp.com|Energy",
  "Shell|shell.com|Energy",
  "Centrica|centrica.com|Energy",
  "National Grid|nationalgrid.com|Utilities",
  "SSE|sse.com|Utilities",
  "EDF UK|edfenergy.com|Utilities",
  "Octopus Energy|octopus.energy|Energy technology",
  "Drax|drax.com|Utilities",
  "Severn Trent|severntrent.com|Utilities",
  "Thames Water|thameswater.co.uk|Utilities",
  "Anglian Water|anglianwater.co.uk|Utilities",
  "United Utilities|unitedutilities.com|Utilities",
  "Network Rail|networkrail.co.uk|Transport",
  "Transport for London|tfl.gov.uk|Transport",
  "British Airways|ba.com|Aviation",
  "easyJet|easyjet.com|Aviation",
  "Ryanair|ryanair.com|Aviation",
  "Jet2|jet2.com|Aviation",
  "Royal Mail|royalmail.com|Logistics",
  "Deliveroo|deliveroo.co.uk|Food delivery",
  "Just Eat Takeaway|justeattakeaway.com|Food delivery",
  "Trainline|thetrainline.com|Travel technology",
  "Expedia|expediagroup.com|Travel technology",
  "Booking.com|booking.com|Travel technology",
  "Airbnb|airbnb.com|Travel technology",
  "Uber|uber.com|Mobility",
  "Spotify|spotify.com|Media technology",
  "Shopify|shopify.com|E-commerce technology",
  "Stripe|stripe.com|Payments",
  "Block|block.xyz|Payments",
  "Adyen|adyen.com|Payments",
  "Klarna|klarna.com|Payments",
  "Revolut|revolut.com|Fintech",
  "Wise|wise.com|Fintech",
  "Checkout.com|checkout.com|Payments",
  "Worldpay|worldpay.com|Payments",
  "FIS|fisglobal.com|Fintech",
  "Fiserv|fiserv.com|Fintech",
  "Global Payments|globalpayments.com|Payments",
  "Experian|experian.com|Credit data",
  "Equifax|equifax.co.uk|Credit data",
  "TransUnion|transunion.co.uk|Credit data",
  "Sage|sage.com|Enterprise software",
  "AVEVA|aveva.com|Industrial software",
  "Endava|endava.com|IT services",
  "Softcat|softcat.com|IT services",
  "Computacenter|computacenter.com|IT services",
  "BJSS|bjss.com|IT services",
  "Thoughtworks|thoughtworks.com|IT services",
  "Publicis Sapient|publicissapient.com|Digital consulting",
  "WPP|wpp.com|Advertising",
  "Dentsu|dentsu.com|Advertising",
  "Informa|informa.com|Information services",
  "RELX|relx.com|Information services",
  "Pearson|pearson.com|Education",
  "Wiley|wiley.com|Publishing",
  "Springer Nature|springernature.com|Publishing",
  "Financial Times|ft.com|Media",
  "The Guardian|theguardian.com|Media",
  "News UK|news.co.uk|Media",
  "Trustpilot|trustpilot.com|Consumer technology",
  "Rightmove|rightmove.co.uk|Property technology",
  "Zoopla|zoopla.co.uk|Property technology",
  "Auto Trader|autotrader.co.uk|Automotive marketplace",
  "MoneySuperMarket|moneysupermarket.com|Comparison",
  "Admiral|admiral.com|Insurance",
  "Direct Line Group|directlinegroup.co.uk|Insurance",
  "IQVIA|iqvia.com|Health data",
  "Arup|arup.com|Engineering",
];

const STARTUPS = [
  "Monzo|monzo.com|Fintech",
  "Starling Bank|starlingbank.com|Fintech",
  "Zopa|zopa.com|Fintech",
  "Tide|tide.co|Fintech",
  "Zilch|zilch.com|Fintech",
  "Freetrade|freetrade.io|Fintech",
  "Moneybox|moneyboxapp.com|Fintech",
  "Plum|withplum.com|Fintech",
  "Marshmallow|marshmallow.com|Insurtech",
  "ClearBank|clear.bank|Fintech",
  "Thought Machine|thoughtmachine.net|Banking technology",
  "10x Banking|10xbanking.com|Banking technology",
  "Form3|form3.tech|Payments",
  "Modulr|modulrfinance.com|Payments",
  "GoCardless|gocardless.com|Payments",
  "TrueLayer|truelayer.com|Open banking",
  "Yapily|yapily.com|Open banking",
  "Paddle|paddle.com|Payments",
  "PrimaryBid|primarybid.com|Fintech",
  "Lendable|lendable.co.uk|Fintech",
  "Capital on Tap|capitalontap.com|Fintech",
  "iwoca|iwoca.co.uk|Fintech",
  "Funding Circle|fundingcircle.com|Fintech",
  "Kriya|kriya.co|Fintech",
  "Codat|codat.io|Fintech infrastructure",
  "Griffin|griffin.com|Banking technology",
  "Elliptic|elliptic.co|Crypto analytics",
  "Chainalysis|chainalysis.com|Crypto analytics",
  "Copper|copper.co|Digital assets",
  "Improbable|improbable.io|Simulation",
  "Builder.ai|builder.ai|AI software",
  "Beamery|beamery.com|HR technology",
  "Multiverse|multiverse.io|Education technology",
  "Cognism|cognism.com|Sales intelligence",
  "Attest|askattest.com|Market research",
  "Peak|peak.ai|AI platform",
  "Faculty|faculty.ai|AI services",
  "Quantexa|quantexa.com|Decision intelligence",
  "Featurespace|featurespace.com|Fraud prevention",
  "Onfido|onfido.com|Identity verification",
  "ComplyAdvantage|complyadvantage.com|RegTech",
  "Hokodo|hokodo.co|Fintech",
  "Sylvera|sylvera.com|Climate data",
  "CarbonChain|carbonchain.com|Climate data",
  "Kaluza|kaluza.com|Energy technology",
  "OVO Energy|ovoenergy.com|Energy",
  "Cleo|meetcleo.com|Fintech",
  "Habito|habito.com|Property technology",
  "Nested|nested.com|Property technology",
  "Goodlord|goodlord.co|Property technology",
  "Houst|houst.com|Property technology",
  "Hometree|hometree.co.uk|Home services",
  "Huma|huma.com|Health technology",
  "Zava|zavamed.com|Health technology",
  "Healx|healx.ai|AI drug discovery",
  "BenevolentAI|benevolent.com|AI drug discovery",
  "Exscientia|exscientia.ai|AI drug discovery",
  "LabGenius|labgeni.us|Biotech",
  "Congenica|congenica.com|Genomics",
  "Cera|ceracare.co.uk|Health technology",
  "Peppy|peppy.health|Health technology",
  "Thriva|thriva.co|Health technology",
  "Numan|numan.com|Health technology",
  "Hinge Health|hingehealth.com|Health technology",
  "Lindus Health|lindushealth.com|Clinical trials",
  "Isomorphic Labs|isomorphiclabs.com|AI drug discovery",
  "Stability AI|stability.ai|Generative AI",
  "Synthesia|synthesia.io|Generative AI",
  "ElevenLabs|elevenlabs.io|Generative AI",
  "PolyAI|poly.ai|Conversational AI",
  "Wayve|wayve.ai|Autonomous driving",
  "Tractable|tractable.ai|Applied AI",
  "V7|v7labs.com|AI data platform",
  "Humanloop|humanloop.com|AI tooling",
  "Luminance|luminance.com|Legal AI",
  "Robin AI|robinai.com|Legal AI",
  "Genie AI|genieai.co|Legal AI",
  "Automata|automata.tech|Lab robotics",
  "Dexory|dexory.com|Robotics",
  "Oxa|oxa.tech|Autonomous vehicles",
  "Graphcore|graphcore.ai|AI hardware",
  "Fractile|fractile.ai|AI hardware",
  "Nscale|nscale.com|AI infrastructure",
  "OpenAI|openai.com|AI research",
  "Anthropic|anthropic.com|AI research",
  "Perplexity|perplexity.ai|AI search",
  "Cohere|cohere.com|AI platform",
  "Hugging Face|huggingface.co|AI platform",
  "Mistral AI|mistral.ai|AI platform",
  "Monese|monese.com|Fintech",
  "Kroo|kroo.com|Fintech",
  "Allica Bank|allica.bank|Banking",
  "OakNorth|oaknorth.co.uk|Banking",
  "Atom Bank|atombank.co.uk|Banking",
  "Zego|zego.com|Insurtech",
  "ManyPets|manypets.com|Insurtech",
  "Cuvva|cuvva.com|Insurtech",
  "Urban Jungle|urbanjungle.insure|Insurtech",
  "Superscript|gosuperscript.com|Insurtech",
  "Ki Insurance|ki-insurance.com|Insurtech",
  "Artificial Labs|artificiallabs.com|Insurtech",
  "Depop|depop.com|Marketplace",
  "Vinted|vinted.com|Marketplace",
  "Carwow|carwow.co.uk|Marketplace",
  "Motorway|motorway.co.uk|Marketplace",
  "Bolt|bolt.eu|Mobility",
  "Snyk|snyk.io|Developer security",
  "Grafana Labs|grafana.com|Observability",
  "Redis|redis.io|Data platform",
  "Neo4j|neo4j.com|Data platform",
  "Elastic|elastic.co|Search platform",
  "Confluent|confluent.io|Data streaming",
  "Docker|docker.com|Developer tools",
  "GitLab|gitlab.com|Developer tools",
  "Sentry|sentry.io|Developer tools",
  "Vercel|vercel.com|Developer platform",
  "Netlify|netlify.com|Developer platform",
  "Supabase|supabase.com|Developer platform",
  "Cockroach Labs|cockroachlabs.com|Data platform",
  "ClickHouse|clickhouse.com|Data platform",
  "Timescale|timescale.com|Data platform",
  "dbt Labs|getdbt.com|Data tooling",
  "Fivetran|fivetran.com|Data integration",
  "Airbyte|airbyte.com|Data integration",
  "Hightouch|hightouch.com|Data activation",
  "Monte Carlo|montecarlodata.com|Data reliability",
  "Hex|hex.tech|Analytics",
  "Metabase|metabase.com|Analytics",
  "Preset|preset.io|Analytics",
  "Starburst|starburst.io|Data platform",
  "Dremio|dremio.com|Data platform",
  "Weaviate|weaviate.io|Vector database",
  "Pinecone|pinecone.io|Vector database",
  "LangChain|langchain.com|AI tooling",
  "Weights & Biases|wandb.ai|ML tooling",
  "Labelbox|labelbox.com|AI data platform",
  "Encord|encord.com|AI data platform",
  "Deel|deel.com|HR technology",
  "Remote|remote.com|HR technology",
  "Oyster|oysterhr.com|HR technology",
  "Papaya Global|papayaglobal.com|HR technology",
  "HiBob|hibob.com|HR technology",
  "CharlieHR|charliehr.com|HR technology",
  "Payfit|payfit.com|HR technology",
  "Pento|pento.io|HR technology",
  "Juro|juro.com|Legal technology",
  "Egress|egress.com|Cyber security",
  "Immersive Labs|immersivelabs.com|Cyber security",
  "Red Sift|redsift.com|Cyber security",
  "Panaseer|panaseer.com|Cyber security",
  "Darktrace|darktrace.com|Cyber security",
  "Bud Financial|bud.co|Fintech",
  "Sonovate|sonovate.com|Fintech",
  "Wagestream|wagestream.com|Fintech",
  "Salary Finance|salaryfinance.com|Fintech",
  "Smart Pension|smart.co|Pensions technology",
  "PensionBee|pensionbee.com|Pensions technology",
  "Penfold|getpenfold.com|Pensions technology",
  "Seccl|seccl.tech|Wealth technology",
  "Seedrs|seedrs.com|Investment platform",
  "Crowdcube|crowdcube.com|Investment platform",
  "Ramp|ramp.com|Fintech",
  "Brex|brex.com|Fintech",
  "Mercury|mercury.com|Fintech",
  "Navan|navan.com|Travel technology",
  "Pleo|pleo.io|Fintech",
  "Soldo|soldo.com|Fintech",
  "Spendesk|spendesk.com|Fintech",
  "Payhawk|payhawk.com|Fintech",
  "Zen Educate|zeneducate.com|Education technology",
  "Century Tech|century.tech|Education technology",
  "Firefly Learning|fireflylearning.com|Education technology",
  "Perlego|perlego.com|Education technology",
  "GoStudent|gostudent.org|Education technology",
  "Preply|preply.com|Education technology",
  "Busuu|busuu.com|Education technology",
  "Supercritical|gosupercritical.com|Climate technology",
  "Newcleo|newcleo.com|Energy technology",
  "Tokamak Energy|tokamakenergy.com|Fusion energy",
  "First Light Fusion|firstlightfusion.com|Fusion energy",
  "Oxford PV|oxfordpv.com|Solar technology",
  "Nyobolt|nyobolt.com|Battery technology",
  "Highview Power|highviewpower.com|Energy storage",
  "Ceres Power|ceres.tech|Hydrogen technology",
  "ITM Power|itm-power.com|Hydrogen technology",
  "Vertical Aerospace|vertical-aerospace.com|Aviation technology",
  "ZeroAvia|zeroavia.com|Aviation technology",
  "Satellite Vu|satellitevu.com|Space technology",
  "Open Cosmos|open-cosmos.com|Space technology",
  "Astroscale UK|astroscale.com|Space technology",
  "Space Forge|spaceforge.co.uk|Space technology",
  "Orbex|orbex.space|Space technology",
  "CMR Surgical|cmrsurgical.com|Medical robotics",
  "Quantinuum|quantinuum.com|Quantum computing",
  "Oxford Quantum Circuits|oqc.tech|Quantum computing",
  "Riverlane|riverlane.com|Quantum computing",
  "Universal Quantum|universalquantum.com|Quantum computing",
  "PsiQuantum|psiquantum.com|Quantum computing",
  "Quantum Motion|quantummotion.tech|Quantum computing",
  "Phasecraft|phasecraft.io|Quantum computing",
];

function parse(lines: string[], group: CompanyGroup): TargetCompany[] {
  return lines.map((line) => {
    const [name, domain, sector] = line.split("|");
    return {
      name: (name ?? "").trim(),
      domain: domain && domain.trim() ? domain.trim() : null,
      sector: (sector ?? "Unknown").trim(),
      group,
    };
  });
}

export const establishedCompanies: TargetCompany[] = parse(ESTABLISHED, "established");
export const startupCompanies: TargetCompany[] = parse(STARTUPS, "startup");
export const targetUniverse: TargetCompany[] = [...establishedCompanies, ...startupCompanies];

export const targetUniverseCounts = {
  established: establishedCompanies.length,
  startup: startupCompanies.length,
  total: targetUniverse.length,
};
